-- SQLite
INSERT INTO turmas (turma, docente) VALUES 
  ('M1A', 'WILLIAM'),
  ('M3A', 'FABIO'),
  ('M3B', 'EPAMINONDAS'),
  ('M1C', 'ROGÉRIO POLETO'),
  ('M3D', 'WALDEMAR'),
  ('M1F', 'ALCINDO'),
  ('M1I', 'BRUNA'),
  ('M1IA', 'LUCAS/GABRIELA'),
  ('M1H', 'IZAIAS'),
  ('T1A', 'LUCIANO'),
  ('T1B', 'DENIS'),
  ('T1C', 'ROGÉRIO POLETO'),
  ('T1D', 'WALDEMAR'),
  ('T1IA', 'MARILIA'),
  ('T1I', 'LUCAS/JOSÉ AUGUSTO'),
  ('T3FA', 'ALEX'),
  ('T2FC', 'FERNANDO'),
  ('T3F', 'VITOR'),
  ('T1FB', 'BRUNO'),
  ('I1F', 'SERGIO'),
  ('I1FA', 'ALEX PENTEADO'),
  ('I1HS', 'MAYCON'),
  ('I1HSB', 'RICARDO'),
  ('I1E', 'JOÃO FLAVIO'),
  ('I2HS', 'ANA'),
  ('N1I', 'MARILIA'),
  ('N3F', 'EVANDRO');